sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: #oss-cn-heyuan.aliyuncs.com
    access-key-secret: 
    access-key-id: 
    bucket-name: #tang-wei
