sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-heyuan.aliyuncs.com
    access-key-secret: lK7IDBMKGdYqlUUfrZXqLnth7b3dTc
    access-key-id: LTAI5tBYh3WdcgJddszYmxNB
    bucket-name: tang-wei
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx7ed3ae13fdff4ab9
    secret: 202c9f4ef173f41bf42fa742dd9e6299